/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nagojudge.app.utils;

import edu.nagojudge.app.exceptions.NagoJudgeException;
import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.Map;
import java.util.ResourceBundle;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.servlet.ServletContext;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.log4j.Logger;

/**
 *
 * @author andresfelipegarciaduran
 */
public class FacesUtil {

    private final Logger logger = Logger.getLogger(FacesUtil.class);

    private static FacesUtil FacesUtil;

    public static FacesUtil getFacesUtil() {
        if (FacesUtil == null) {
            FacesUtil = new FacesUtil();
        }
        return FacesUtil;
    }

    public void redirect(String path) throws IOException {

        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(path);
        } catch (IOException ex) {
            logger.error(ex);
            throw ex;
        }

    }

    public String getRealPath() {
        return FacesContext.getCurrentInstance().getExternalContext().getRealPath("/");
    }

    public String getContextPath() {
        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        return servletContext.getContextPath();
    }

    public String getRequestURI() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        return request.getRequestURI();
    }

    public String getRequestContextPath() {
        return FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath();
    }

    public void addMessage(FacesMessage.Severity severity, String messageBold) {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(severity, messageBold, null));
    }

    public Map<String, Object> getRequestMap() {
        Map<String, Object> requestMap = FacesContext.getCurrentInstance().getExternalContext().getRequestMap();
        return requestMap;
    }

    public Flash getFlash() {
        Flash flash = FacesContext.getCurrentInstance().getExternalContext().getFlash();
        return flash;
    }

    public Map<String, Object> getSessionMap() {
        Map<String, Object> requestMap = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
        return requestMap;
    }

    public HttpSession getCurrentSession() {
        HttpServletRequest request = getRequest();
        return request.getSession();
    }

    public HttpSession getSession(boolean state) {
        HttpServletRequest request = getRequest();
        return request.getSession(state);
    }

    public Object getAttributeCurrentSession(String attribute) {
        return getCurrentSession().getAttribute(attribute);
    }

    public HttpServletRequest getRequest() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        return request;
    }

    public HttpServletResponse getResponse() {
        HttpServletResponse response = (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();
        return response;
    }

    public String getResourceBundle(String key, String basename) {
        ResourceBundle text = ResourceBundle.getBundle(basename, FacesContext.getCurrentInstance().getViewRoot().getLocale());
        return text.getString(key);
    }

    public String getInitParameter(String key) {
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        String initParameter = externalContext.getInitParameter(key);
        return initParameter;
    }

    public boolean isValidationFailed() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        return facesContext.isPostback() && facesContext.isValidationFailed();
    }

    public void printErrorResponse(String message) {
        NagoJudgeException nagoJudgeException = new NagoJudgeException(message);
        sendProcessingError(nagoJudgeException, getResponse());
    }

    public void printErrorResponse(Throwable throwable, ServletResponse response) {
        sendProcessingError(throwable, response);
    }

    private void sendProcessingError(Throwable t, ServletResponse response) {
        try {
            logger.debug("INICIA METODO - sendProcessingError()");
            String messageThrowable = t.getMessage();
            if (messageThrowable != null && !messageThrowable.equals("")) {
                PrintStream printStream = null;
                PrintWriter printWriter = null;
                try {
                    response.setContentType("text/html");
                    printStream = new PrintStream(response.getOutputStream());
                    printWriter = new PrintWriter(printStream);
                    StringBuilder html = new StringBuilder();
                    /*
                    html.append("<html>"
                            + "<head>"
                            + "  <meta content='text/html; charset=UTF-8' http-equiv=\"Content-Type\"/>\n"
                            + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
                            + "  <link rel=\"stylesheet\" href=\"/go/to/tools/frameworks/bootstrap/css/lumen/bootstrap.min.css\"/>\n"
                            + "  <script src=\"/go/to/tools/frameworks/bootstrap/js/bootstrap.min.js\"></script>\n"
                            + "  <link rel=\"icon\" type=\"image/ico\" href=\"/go/to/img/logo-icon.png\"/>"
                            + "  <title>Nago Judge</title>"
                            + "</head>"
                            + "<body>"
                            + "<div class=\"container\">\n"
                            + "    <div class=\"row\">\n"
                            + "        <div class=\"col-md-12\">\n"
                            + "            <div class=\"error-template\">\n"
                            + "                <div class=\"error-details\">\n"
                            + "<h1> " + messageThrowable + "</h1>\n"
                            + "                </div>\n"
                            + "                <div class=\"error-actions\">\n"
                            + "                    <a href=\"/go/to/home.xhtml\" class=\"btn btn-primary btn-lg\"><span class=\"glyphicon glyphicon-home\"></span>\n Return to home </a>"
                            + "                </div>\n"
                            + "            </div>\n"
                            + "        </div>\n"
                            + "    </div>\n"
                            + "</div>"
                            + "</body>"
                            + "</html>");
                     */
                    html.append(
                            "<head>"
                            + "  <meta content='text/html; charset=UTF-8' http-equiv=\"Content-Type\"/>\n"
                            + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
                            + "  <link rel=\"icon\" type=\"image/ico\" href=\"/go/to/img/logo-icon.png\"/>"
                            + "  <title>Nago Judge</title>"
                            + " <style>\n"
                            + "@import url(\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic\");\n"
                            + "html {\n"
                            + "  font-family: sans-serif;\n"
                            + "  -ms-text-size-adjust: 100%;\n"
                            + "  -webkit-text-size-adjust: 100%;\n"
                            + "}\n"
                            + "body {\n"
                            + "  margin: 0;\n"
                            + "}\n"
                            + "article,\n"
                            + "aside,\n"
                            + "details,\n"
                            + "figcaption,\n"
                            + "figure,\n"
                            + "footer,\n"
                            + "header,\n"
                            + "hgroup,\n"
                            + "main,\n"
                            + "menu,\n"
                            + "nav,\n"
                            + "section,\n"
                            + "summary {\n"
                            + "  display: block;\n"
                            + "}\n"
                            + "audio,\n"
                            + "canvas,\n"
                            + "progress,\n"
                            + "video {\n"
                            + "  display: inline-block;\n"
                            + "  vertical-align: baseline;\n"
                            + "}\n"
                            + "audio:not([controls]) {\n"
                            + "  display: none;\n"
                            + "  height: 0;\n"
                            + "}\n"
                            + "[hidden],\n"
                            + "template {\n"
                            + "  display: none;\n"
                            + "}\n"
                            + "a {\n"
                            + "  background-color: transparent;\n"
                            + "}\n"
                            + "a:active,\n"
                            + "a:hover {\n"
                            + "  outline: 0;\n"
                            + "}\n"
                            + "abbr[title] {\n"
                            + "  border-bottom: 1px dotted;\n"
                            + "}\n"
                            + "b,\n"
                            + "strong {\n"
                            + "  font-weight: bold;\n"
                            + "}\n"
                            + "dfn {\n"
                            + "  font-style: italic;\n"
                            + "}\n"
                            + "h1 {\n"
                            + "  font-size: 2em;\n"
                            + "  margin: 0.67em 0;\n"
                            + "}\n"
                            + "mark {\n"
                            + "  background: #ff0;\n"
                            + "  color: #000;\n"
                            + "}\n"
                            + "small {\n"
                            + "  font-size: 80%;\n"
                            + "}\n"
                            + "sub,\n"
                            + "sup {\n"
                            + "  font-size: 75%;\n"
                            + "  line-height: 0;\n"
                            + "  position: relative;\n"
                            + "  vertical-align: baseline;\n"
                            + "}\n"
                            + "sup {\n"
                            + "  top: -0.5em;\n"
                            + "}\n"
                            + "sub {\n"
                            + "  bottom: -0.25em;\n"
                            + "}\n"
                            + "img {\n"
                            + "  border: 0;\n"
                            + "}\n"
                            + "svg:not(:root) {\n"
                            + "  overflow: hidden;\n"
                            + "}\n"
                            + "figure {\n"
                            + "  margin: 1em 40px;\n"
                            + "}\n"
                            + "hr {\n"
                            + "  -webkit-box-sizing: content-box;\n"
                            + "     -moz-box-sizing: content-box;\n"
                            + "          box-sizing: content-box;\n"
                            + "  height: 0;\n"
                            + "}\n"
                            + "pre {\n"
                            + "  overflow: auto;\n"
                            + "}\n"
                            + "code,\n"
                            + "kbd,\n"
                            + "pre,\n"
                            + "samp {\n"
                            + "  font-family: monospace, monospace;\n"
                            + "  font-size: 1em;\n"
                            + "}\n"
                            + "button,\n"
                            + "input,\n"
                            + "optgroup,\n"
                            + "select,\n"
                            + "textarea {\n"
                            + "  color: inherit;\n"
                            + "  font: inherit;\n"
                            + "  margin: 0;\n"
                            + "}\n"
                            + "button {\n"
                            + "  overflow: visible;\n"
                            + "}\n"
                            + "button,\n"
                            + "select {\n"
                            + "  text-transform: none;\n"
                            + "}\n"
                            + "button,\n"
                            + "html input[type=\"button\"],\n"
                            + "input[type=\"reset\"],\n"
                            + "input[type=\"submit\"] {\n"
                            + "  -webkit-appearance: button;\n"
                            + "  cursor: pointer;\n"
                            + "}\n"
                            + "button[disabled],\n"
                            + "html input[disabled] {\n"
                            + "  cursor: default;\n"
                            + "}\n"
                            + "button::-moz-focus-inner,\n"
                            + "input::-moz-focus-inner {\n"
                            + "  border: 0;\n"
                            + "  padding: 0;\n"
                            + "}\n"
                            + "input {\n"
                            + "  line-height: normal;\n"
                            + "}\n"
                            + "input[type=\"checkbox\"],\n"
                            + "input[type=\"radio\"] {\n"
                            + "  -webkit-box-sizing: border-box;\n"
                            + "     -moz-box-sizing: border-box;\n"
                            + "          box-sizing: border-box;\n"
                            + "  padding: 0;\n"
                            + "}\n"
                            + "input[type=\"number\"]::-webkit-inner-spin-button,\n"
                            + "input[type=\"number\"]::-webkit-outer-spin-button {\n"
                            + "  height: auto;\n"
                            + "}\n"
                            + "input[type=\"search\"] {\n"
                            + "  -webkit-appearance: textfield;\n"
                            + "  -webkit-box-sizing: content-box;\n"
                            + "     -moz-box-sizing: content-box;\n"
                            + "          box-sizing: content-box;\n"
                            + "}\n"
                            + "input[type=\"search\"]::-webkit-search-cancel-button,\n"
                            + "input[type=\"search\"]::-webkit-search-decoration {\n"
                            + "  -webkit-appearance: none;\n"
                            + "}\n"
                            + "fieldset {\n"
                            + "  border: 1px solid #c0c0c0;\n"
                            + "  margin: 0 2px;\n"
                            + "  padding: 0.35em 0.625em 0.75em;\n"
                            + "}\n"
                            + "legend {\n"
                            + "  border: 0;\n"
                            + "  padding: 0;\n"
                            + "}\n"
                            + "textarea {\n"
                            + "  overflow: auto;\n"
                            + "}\n"
                            + "optgroup {\n"
                            + "  font-weight: bold;\n"
                            + "}\n"
                            + "table {\n"
                            + "  border-collapse: collapse;\n"
                            + "  border-spacing: 0;\n"
                            + "}\n"
                            + "td,\n"
                            + "th {\n"
                            + "  padding: 0;\n"
                            + "}\n"
                            + "/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */\n"
                            + "@media print {\n"
                            + "  *,\n"
                            + "  *:before,\n"
                            + "  *:after {\n"
                            + "    background: transparent !important;\n"
                            + "    color: #000 !important;\n"
                            + "    -webkit-box-shadow: none !important;\n"
                            + "            box-shadow: none !important;\n"
                            + "    text-shadow: none !important;\n"
                            + "  }\n"
                            + "  a,\n"
                            + "  a:visited {\n"
                            + "    text-decoration: underline;\n"
                            + "  }\n"
                            + "  a[href]:after {\n"
                            + "    content: \" (\" attr(href) \")\";\n"
                            + "  }\n"
                            + "  abbr[title]:after {\n"
                            + "    content: \" (\" attr(title) \")\";\n"
                            + "  }\n"
                            + "  a[href^=\"#\"]:after,\n"
                            + "  a[href^=\"javascript:\"]:after {\n"
                            + "    content: \"\";\n"
                            + "  }\n"
                            + "  pre,\n"
                            + "  blockquote {\n"
                            + "    border: 1px solid #999;\n"
                            + "    page-break-inside: avoid;\n"
                            + "  }\n"
                            + "  thead {\n"
                            + "    display: table-header-group;\n"
                            + "  }\n"
                            + "  tr,\n"
                            + "  img {\n"
                            + "    page-break-inside: avoid;\n"
                            + "  }\n"
                            + "  img {\n"
                            + "    max-width: 100% !important;\n"
                            + "  }\n"
                            + "  p,\n"
                            + "  h2,\n"
                            + "  h3 {\n"
                            + "    orphans: 3;\n"
                            + "    widows: 3;\n"
                            + "  }\n"
                            + "  h2,\n"
                            + "  h3 {\n"
                            + "    page-break-after: avoid;\n"
                            + "  }\n"
                            + "  .navbar {\n"
                            + "    display: none;\n"
                            + "  }\n"
                            + "  .btn > .caret,\n"
                            + "  .dropup > .btn > .caret {\n"
                            + "    border-top-color: #000 !important;\n"
                            + "  }\n"
                            + "  .label {\n"
                            + "    border: 1px solid #000;\n"
                            + "  }\n"
                            + "  .table {\n"
                            + "    border-collapse: collapse !important;\n"
                            + "  }\n"
                            + "  .table td,\n"
                            + "  .table th {\n"
                            + "    background-color: #fff !important;\n"
                            + "  }\n"
                            + "  .table-bordered th,\n"
                            + "  .table-bordered td {\n"
                            + "    border: 1px solid #ddd !important;\n"
                            + "  }\n"
                            + "}\n"
                            + "@font-face {\n"
                            + "  font-family: 'Glyphicons Halflings';\n"
                            + "  src: url('../fonts/glyphicons-halflings-regular.eot');\n"
                            + "  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');\n"
                            + "}\n"
                            + ".glyphicon {\n"
                            + "  position: relative;\n"
                            + "  top: 1px;\n"
                            + "  display: inline-block;\n"
                            + "  font-family: 'Glyphicons Halflings';\n"
                            + "  font-style: normal;\n"
                            + "  font-weight: normal;\n"
                            + "  line-height: 1;\n"
                            + "  -webkit-font-smoothing: antialiased;\n"
                            + "  -moz-osx-font-smoothing: grayscale;\n"
                            + "}\n"
                            + ".glyphicon-asterisk:before {\n"
                            + "  content: \"\\002a\";\n"
                            + "}\n"
                            + ".glyphicon-plus:before {\n"
                            + "  content: \"\\002b\";\n"
                            + "}\n"
                            + ".glyphicon-euro:before,\n"
                            + ".glyphicon-eur:before {\n"
                            + "  content: \"\\20ac\";\n"
                            + "}\n"
                            + ".glyphicon-minus:before {\n"
                            + "  content: \"\\2212\";\n"
                            + "}\n"
                            + ".glyphicon-cloud:before {\n"
                            + "  content: \"\\2601\";\n"
                            + "}\n"
                            + ".glyphicon-envelope:before {\n"
                            + "  content: \"\\2709\";\n"
                            + "}\n"
                            + ".glyphicon-pencil:before {\n"
                            + "  content: \"\\270f\";\n"
                            + "}\n"
                            + ".glyphicon-glass:before {\n"
                            + "  content: \"\\e001\";\n"
                            + "}\n"
                            + ".glyphicon-music:before {\n"
                            + "  content: \"\\e002\";\n"
                            + "}\n"
                            + ".glyphicon-search:before {\n"
                            + "  content: \"\\e003\";\n"
                            + "}\n"
                            + ".glyphicon-heart:before {\n"
                            + "  content: \"\\e005\";\n"
                            + "}\n"
                            + ".glyphicon-star:before {\n"
                            + "  content: \"\\e006\";\n"
                            + "}\n"
                            + ".glyphicon-star-empty:before {\n"
                            + "  content: \"\\e007\";\n"
                            + "}\n"
                            + ".glyphicon-user:before {\n"
                            + "  content: \"\\e008\";\n"
                            + "}\n"
                            + ".glyphicon-film:before {\n"
                            + "  content: \"\\e009\";\n"
                            + "}\n"
                            + ".glyphicon-th-large:before {\n"
                            + "  content: \"\\e010\";\n"
                            + "}\n"
                            + ".glyphicon-th:before {\n"
                            + "  content: \"\\e011\";\n"
                            + "}\n"
                            + ".glyphicon-th-list:before {\n"
                            + "  content: \"\\e012\";\n"
                            + "}\n"
                            + ".glyphicon-ok:before {\n"
                            + "  content: \"\\e013\";\n"
                            + "}\n"
                            + ".glyphicon-remove:before {\n"
                            + "  content: \"\\e014\";\n"
                            + "}\n"
                            + ".glyphicon-zoom-in:before {\n"
                            + "  content: \"\\e015\";\n"
                            + "}\n"
                            + ".glyphicon-zoom-out:before {\n"
                            + "  content: \"\\e016\";\n"
                            + "}\n"
                            + ".glyphicon-off:before {\n"
                            + "  content: \"\\e017\";\n"
                            + "}\n"
                            + ".glyphicon-signal:before {\n"
                            + "  content: \"\\e018\";\n"
                            + "}\n"
                            + ".glyphicon-cog:before {\n"
                            + "  content: \"\\e019\";\n"
                            + "}\n"
                            + ".glyphicon-trash:before {\n"
                            + "  content: \"\\e020\";\n"
                            + "}\n"
                            + ".glyphicon-home:before {\n"
                            + "  content: \"\\e021\";\n"
                            + "}\n"
                            + ".glyphicon-file:before {\n"
                            + "  content: \"\\e022\";\n"
                            + "}\n"
                            + ".glyphicon-time:before {\n"
                            + "  content: \"\\e023\";\n"
                            + "}\n"
                            + ".glyphicon-road:before {\n"
                            + "  content: \"\\e024\";\n"
                            + "}\n"
                            + ".glyphicon-download-alt:before {\n"
                            + "  content: \"\\e025\";\n"
                            + "}\n"
                            + ".glyphicon-download:before {\n"
                            + "  content: \"\\e026\";\n"
                            + "}\n"
                            + ".glyphicon-upload:before {\n"
                            + "  content: \"\\e027\";\n"
                            + "}\n"
                            + ".glyphicon-inbox:before {\n"
                            + "  content: \"\\e028\";\n"
                            + "}\n"
                            + ".glyphicon-play-circle:before {\n"
                            + "  content: \"\\e029\";\n"
                            + "}\n"
                            + ".glyphicon-repeat:before {\n"
                            + "  content: \"\\e030\";\n"
                            + "}\n"
                            + ".glyphicon-refresh:before {\n"
                            + "  content: \"\\e031\";\n"
                            + "}\n"
                            + ".glyphicon-list-alt:before {\n"
                            + "  content: \"\\e032\";\n"
                            + "}\n"
                            + ".glyphicon-lock:before {\n"
                            + "  content: \"\\e033\";\n"
                            + "}\n"
                            + ".glyphicon-flag:before {\n"
                            + "  content: \"\\e034\";\n"
                            + "}\n"
                            + ".glyphicon-headphones:before {\n"
                            + "  content: \"\\e035\";\n"
                            + "}\n"
                            + ".glyphicon-volume-off:before {\n"
                            + "  content: \"\\e036\";\n"
                            + "}\n"
                            + ".glyphicon-volume-down:before {\n"
                            + "  content: \"\\e037\";\n"
                            + "}\n"
                            + ".glyphicon-volume-up:before {\n"
                            + "  content: \"\\e038\";\n"
                            + "}\n"
                            + ".glyphicon-qrcode:before {\n"
                            + "  content: \"\\e039\";\n"
                            + "}\n"
                            + ".glyphicon-barcode:before {\n"
                            + "  content: \"\\e040\";\n"
                            + "}\n"
                            + ".glyphicon-tag:before {\n"
                            + "  content: \"\\e041\";\n"
                            + "}\n"
                            + ".glyphicon-tags:before {\n"
                            + "  content: \"\\e042\";\n"
                            + "}\n"
                            + ".glyphicon-book:before {\n"
                            + "  content: \"\\e043\";\n"
                            + "}\n"
                            + ".glyphicon-bookmark:before {\n"
                            + "  content: \"\\e044\";\n"
                            + "}\n"
                            + ".glyphicon-print:before {\n"
                            + "  content: \"\\e045\";\n"
                            + "}\n"
                            + ".glyphicon-camera:before {\n"
                            + "  content: \"\\e046\";\n"
                            + "}\n"
                            + ".glyphicon-font:before {\n"
                            + "  content: \"\\e047\";\n"
                            + "}\n"
                            + ".glyphicon-bold:before {\n"
                            + "  content: \"\\e048\";\n"
                            + "}\n"
                            + ".glyphicon-italic:before {\n"
                            + "  content: \"\\e049\";\n"
                            + "}\n"
                            + ".glyphicon-text-height:before {\n"
                            + "  content: \"\\e050\";\n"
                            + "}\n"
                            + ".glyphicon-text-width:before {\n"
                            + "  content: \"\\e051\";\n"
                            + "}\n"
                            + ".glyphicon-align-left:before {\n"
                            + "  content: \"\\e052\";\n"
                            + "}\n"
                            + ".glyphicon-align-center:before {\n"
                            + "  content: \"\\e053\";\n"
                            + "}\n"
                            + ".glyphicon-align-right:before {\n"
                            + "  content: \"\\e054\";\n"
                            + "}\n"
                            + ".glyphicon-align-justify:before {\n"
                            + "  content: \"\\e055\";\n"
                            + "}\n"
                            + ".glyphicon-list:before {\n"
                            + "  content: \"\\e056\";\n"
                            + "}\n"
                            + ".glyphicon-indent-left:before {\n"
                            + "  content: \"\\e057\";\n"
                            + "}\n"
                            + ".glyphicon-indent-right:before {\n"
                            + "  content: \"\\e058\";\n"
                            + "}\n"
                            + ".glyphicon-facetime-video:before {\n"
                            + "  content: \"\\e059\";\n"
                            + "}\n"
                            + ".glyphicon-picture:before {\n"
                            + "  content: \"\\e060\";\n"
                            + "}\n"
                            + ".glyphicon-map-marker:before {\n"
                            + "  content: \"\\e062\";\n"
                            + "}\n"
                            + ".glyphicon-adjust:before {\n"
                            + "  content: \"\\e063\";\n"
                            + "}\n"
                            + ".glyphicon-tint:before {\n"
                            + "  content: \"\\e064\";\n"
                            + "}\n"
                            + ".glyphicon-edit:before {\n"
                            + "  content: \"\\e065\";\n"
                            + "}\n"
                            + ".glyphicon-share:before {\n"
                            + "  content: \"\\e066\";\n"
                            + "}\n"
                            + ".glyphicon-check:before {\n"
                            + "  content: \"\\e067\";\n"
                            + "}\n"
                            + ".glyphicon-move:before {\n"
                            + "  content: \"\\e068\";\n"
                            + "}\n"
                            + ".glyphicon-step-backward:before {\n"
                            + "  content: \"\\e069\";\n"
                            + "}\n"
                            + ".glyphicon-fast-backward:before {\n"
                            + "  content: \"\\e070\";\n"
                            + "}\n"
                            + ".glyphicon-backward:before {\n"
                            + "  content: \"\\e071\";\n"
                            + "}\n"
                            + ".glyphicon-play:before {\n"
                            + "  content: \"\\e072\";\n"
                            + "}\n"
                            + ".glyphicon-pause:before {\n"
                            + "  content: \"\\e073\";\n"
                            + "}\n"
                            + ".glyphicon-stop:before {\n"
                            + "  content: \"\\e074\";\n"
                            + "}\n"
                            + ".glyphicon-forward:before {\n"
                            + "  content: \"\\e075\";\n"
                            + "}\n"
                            + ".glyphicon-fast-forward:before {\n"
                            + "  content: \"\\e076\";\n"
                            + "}\n"
                            + ".glyphicon-step-forward:before {\n"
                            + "  content: \"\\e077\";\n"
                            + "}\n"
                            + ".glyphicon-eject:before {\n"
                            + "  content: \"\\e078\";\n"
                            + "}\n"
                            + ".glyphicon-chevron-left:before {\n"
                            + "  content: \"\\e079\";\n"
                            + "}\n"
                            + ".glyphicon-chevron-right:before {\n"
                            + "  content: \"\\e080\";\n"
                            + "}\n"
                            + ".glyphicon-plus-sign:before {\n"
                            + "  content: \"\\e081\";\n"
                            + "}\n"
                            + ".glyphicon-minus-sign:before {\n"
                            + "  content: \"\\e082\";\n"
                            + "}\n"
                            + ".glyphicon-remove-sign:before {\n"
                            + "  content: \"\\e083\";\n"
                            + "}\n"
                            + ".glyphicon-ok-sign:before {\n"
                            + "  content: \"\\e084\";\n"
                            + "}\n"
                            + ".glyphicon-question-sign:before {\n"
                            + "  content: \"\\e085\";\n"
                            + "}\n"
                            + ".glyphicon-info-sign:before {\n"
                            + "  content: \"\\e086\";\n"
                            + "}\n"
                            + ".glyphicon-screenshot:before {\n"
                            + "  content: \"\\e087\";\n"
                            + "}\n"
                            + ".glyphicon-remove-circle:before {\n"
                            + "  content: \"\\e088\";\n"
                            + "}\n"
                            + ".glyphicon-ok-circle:before {\n"
                            + "  content: \"\\e089\";\n"
                            + "}\n"
                            + ".glyphicon-ban-circle:before {\n"
                            + "  content: \"\\e090\";\n"
                            + "}\n"
                            + ".glyphicon-arrow-left:before {\n"
                            + "  content: \"\\e091\";\n"
                            + "}\n"
                            + ".glyphicon-arrow-right:before {\n"
                            + "  content: \"\\e092\";\n"
                            + "}\n"
                            + ".glyphicon-arrow-up:before {\n"
                            + "  content: \"\\e093\";\n"
                            + "}\n"
                            + ".glyphicon-arrow-down:before {\n"
                            + "  content: \"\\e094\";\n"
                            + "}\n"
                            + ".glyphicon-share-alt:before {\n"
                            + "  content: \"\\e095\";\n"
                            + "}\n"
                            + ".glyphicon-resize-full:before {\n"
                            + "  content: \"\\e096\";\n"
                            + "}\n"
                            + ".glyphicon-resize-small:before {\n"
                            + "  content: \"\\e097\";\n"
                            + "}\n"
                            + ".glyphicon-exclamation-sign:before {\n"
                            + "  content: \"\\e101\";\n"
                            + "}\n"
                            + ".glyphicon-gift:before {\n"
                            + "  content: \"\\e102\";\n"
                            + "}\n"
                            + ".glyphicon-leaf:before {\n"
                            + "  content: \"\\e103\";\n"
                            + "}\n"
                            + ".glyphicon-fire:before {\n"
                            + "  content: \"\\e104\";\n"
                            + "}\n"
                            + ".glyphicon-eye-open:before {\n"
                            + "  content: \"\\e105\";\n"
                            + "}\n"
                            + ".glyphicon-eye-close:before {\n"
                            + "  content: \"\\e106\";\n"
                            + "}\n"
                            + ".glyphicon-warning-sign:before {\n"
                            + "  content: \"\\e107\";\n"
                            + "}\n"
                            + ".glyphicon-plane:before {\n"
                            + "  content: \"\\e108\";\n"
                            + "}\n"
                            + ".glyphicon-calendar:before {\n"
                            + "  content: \"\\e109\";\n"
                            + "}\n"
                            + ".glyphicon-random:before {\n"
                            + "  content: \"\\e110\";\n"
                            + "}\n"
                            + ".glyphicon-comment:before {\n"
                            + "  content: \"\\e111\";\n"
                            + "}\n"
                            + ".glyphicon-magnet:before {\n"
                            + "  content: \"\\e112\";\n"
                            + "}\n"
                            + ".glyphicon-chevron-up:before {\n"
                            + "  content: \"\\e113\";\n"
                            + "}\n"
                            + ".glyphicon-chevron-down:before {\n"
                            + "  content: \"\\e114\";\n"
                            + "}\n"
                            + ".glyphicon-retweet:before {\n"
                            + "  content: \"\\e115\";\n"
                            + "}\n"
                            + ".glyphicon-shopping-cart:before {\n"
                            + "  content: \"\\e116\";\n"
                            + "}\n"
                            + ".glyphicon-folder-close:before {\n"
                            + "  content: \"\\e117\";\n"
                            + "}\n"
                            + ".glyphicon-folder-open:before {\n"
                            + "  content: \"\\e118\";\n"
                            + "}\n"
                            + ".glyphicon-resize-vertical:before {\n"
                            + "  content: \"\\e119\";\n"
                            + "}\n"
                            + ".glyphicon-resize-horizontal:before {\n"
                            + "  content: \"\\e120\";\n"
                            + "}\n"
                            + ".glyphicon-hdd:before {\n"
                            + "  content: \"\\e121\";\n"
                            + "}\n"
                            + ".glyphicon-bullhorn:before {\n"
                            + "  content: \"\\e122\";\n"
                            + "}\n"
                            + ".glyphicon-bell:before {\n"
                            + "  content: \"\\e123\";\n"
                            + "}\n"
                            + ".glyphicon-certificate:before {\n"
                            + "  content: \"\\e124\";\n"
                            + "}\n"
                            + ".glyphicon-thumbs-up:before {\n"
                            + "  content: \"\\e125\";\n"
                            + "}\n"
                            + ".glyphicon-thumbs-down:before {\n"
                            + "  content: \"\\e126\";\n"
                            + "}\n"
                            + ".glyphicon-hand-right:before {\n"
                            + "  content: \"\\e127\";\n"
                            + "}\n"
                            + ".glyphicon-hand-left:before {\n"
                            + "  content: \"\\e128\";\n"
                            + "}\n"
                            + ".glyphicon-hand-up:before {\n"
                            + "  content: \"\\e129\";\n"
                            + "}\n"
                            + ".glyphicon-hand-down:before {\n"
                            + "  content: \"\\e130\";\n"
                            + "}\n"
                            + ".glyphicon-circle-arrow-right:before {\n"
                            + "  content: \"\\e131\";\n"
                            + "}\n"
                            + ".glyphicon-circle-arrow-left:before {\n"
                            + "  content: \"\\e132\";\n"
                            + "}\n"
                            + ".glyphicon-circle-arrow-up:before {\n"
                            + "  content: \"\\e133\";\n"
                            + "}\n"
                            + ".glyphicon-circle-arrow-down:before {\n"
                            + "  content: \"\\e134\";\n"
                            + "}\n"
                            + ".glyphicon-globe:before {\n"
                            + "  content: \"\\e135\";\n"
                            + "}\n"
                            + ".glyphicon-wrench:before {\n"
                            + "  content: \"\\e136\";\n"
                            + "}\n"
                            + ".glyphicon-tasks:before {\n"
                            + "  content: \"\\e137\";\n"
                            + "}\n"
                            + ".glyphicon-filter:before {\n"
                            + "  content: \"\\e138\";\n"
                            + "}\n"
                            + ".glyphicon-briefcase:before {\n"
                            + "  content: \"\\e139\";\n"
                            + "}\n"
                            + ".glyphicon-fullscreen:before {\n"
                            + "  content: \"\\e140\";\n"
                            + "}\n"
                            + ".glyphicon-dashboard:before {\n"
                            + "  content: \"\\e141\";\n"
                            + "}\n"
                            + ".glyphicon-paperclip:before {\n"
                            + "  content: \"\\e142\";\n"
                            + "}\n"
                            + ".glyphicon-heart-empty:before {\n"
                            + "  content: \"\\e143\";\n"
                            + "}\n"
                            + ".glyphicon-link:before {\n"
                            + "  content: \"\\e144\";\n"
                            + "}\n"
                            + ".glyphicon-phone:before {\n"
                            + "  content: \"\\e145\";\n"
                            + "}\n"
                            + ".glyphicon-pushpin:before {\n"
                            + "  content: \"\\e146\";\n"
                            + "}\n"
                            + ".glyphicon-usd:before {\n"
                            + "  content: \"\\e148\";\n"
                            + "}\n"
                            + ".glyphicon-gbp:before {\n"
                            + "  content: \"\\e149\";\n"
                            + "}\n"
                            + ".glyphicon-sort:before {\n"
                            + "  content: \"\\e150\";\n"
                            + "}\n"
                            + ".glyphicon-sort-by-alphabet:before {\n"
                            + "  content: \"\\e151\";\n"
                            + "}\n"
                            + ".glyphicon-sort-by-alphabet-alt:before {\n"
                            + "  content: \"\\e152\";\n"
                            + "}\n"
                            + ".glyphicon-sort-by-order:before {\n"
                            + "  content: \"\\e153\";\n"
                            + "}\n"
                            + ".glyphicon-sort-by-order-alt:before {\n"
                            + "  content: \"\\e154\";\n"
                            + "}\n"
                            + ".glyphicon-sort-by-attributes:before {\n"
                            + "  content: \"\\e155\";\n"
                            + "}\n"
                            + ".glyphicon-sort-by-attributes-alt:before {\n"
                            + "  content: \"\\e156\";\n"
                            + "}\n"
                            + ".glyphicon-unchecked:before {\n"
                            + "  content: \"\\e157\";\n"
                            + "}\n"
                            + ".glyphicon-expand:before {\n"
                            + "  content: \"\\e158\";\n"
                            + "}\n"
                            + ".glyphicon-collapse-down:before {\n"
                            + "  content: \"\\e159\";\n"
                            + "}\n"
                            + ".glyphicon-collapse-up:before {\n"
                            + "  content: \"\\e160\";\n"
                            + "}\n"
                            + ".glyphicon-log-in:before {\n"
                            + "  content: \"\\e161\";\n"
                            + "}\n"
                            + ".glyphicon-flash:before {\n"
                            + "  content: \"\\e162\";\n"
                            + "}\n"
                            + ".glyphicon-log-out:before {\n"
                            + "  content: \"\\e163\";\n"
                            + "}\n"
                            + ".glyphicon-new-window:before {\n"
                            + "  content: \"\\e164\";\n"
                            + "}\n"
                            + ".glyphicon-record:before {\n"
                            + "  content: \"\\e165\";\n"
                            + "}\n"
                            + ".glyphicon-save:before {\n"
                            + "  content: \"\\e166\";\n"
                            + "}\n"
                            + ".glyphicon-open:before {\n"
                            + "  content: \"\\e167\";\n"
                            + "}\n"
                            + ".glyphicon-saved:before {\n"
                            + "  content: \"\\e168\";\n"
                            + "}\n"
                            + ".glyphicon-import:before {\n"
                            + "  content: \"\\e169\";\n"
                            + "}\n"
                            + ".glyphicon-export:before {\n"
                            + "  content: \"\\e170\";\n"
                            + "}\n"
                            + ".glyphicon-send:before {\n"
                            + "  content: \"\\e171\";\n"
                            + "}\n"
                            + ".glyphicon-floppy-disk:before {\n"
                            + "  content: \"\\e172\";\n"
                            + "}\n"
                            + ".glyphicon-floppy-saved:before {\n"
                            + "  content: \"\\e173\";\n"
                            + "}\n"
                            + ".glyphicon-floppy-remove:before {\n"
                            + "  content: \"\\e174\";\n"
                            + "}\n"
                            + ".glyphicon-floppy-save:before {\n"
                            + "  content: \"\\e175\";\n"
                            + "}\n"
                            + ".glyphicon-floppy-open:before {\n"
                            + "  content: \"\\e176\";\n"
                            + "}\n"
                            + ".glyphicon-credit-card:before {\n"
                            + "  content: \"\\e177\";\n"
                            + "}\n"
                            + ".glyphicon-transfer:before {\n"
                            + "  content: \"\\e178\";\n"
                            + "}\n"
                            + ".glyphicon-cutlery:before {\n"
                            + "  content: \"\\e179\";\n"
                            + "}\n"
                            + ".glyphicon-header:before {\n"
                            + "  content: \"\\e180\";\n"
                            + "}\n"
                            + ".glyphicon-compressed:before {\n"
                            + "  content: \"\\e181\";\n"
                            + "}\n"
                            + ".glyphicon-earphone:before {\n"
                            + "  content: \"\\e182\";\n"
                            + "}\n"
                            + ".glyphicon-phone-alt:before {\n"
                            + "  content: \"\\e183\";\n"
                            + "}\n"
                            + ".glyphicon-tower:before {\n"
                            + "  content: \"\\e184\";\n"
                            + "}\n"
                            + ".glyphicon-stats:before {\n"
                            + "  content: \"\\e185\";\n"
                            + "}\n"
                            + ".glyphicon-sd-video:before {\n"
                            + "  content: \"\\e186\";\n"
                            + "}\n"
                            + ".glyphicon-hd-video:before {\n"
                            + "  content: \"\\e187\";\n"
                            + "}\n"
                            + ".glyphicon-subtitles:before {\n"
                            + "  content: \"\\e188\";\n"
                            + "}\n"
                            + ".glyphicon-sound-stereo:before {\n"
                            + "  content: \"\\e189\";\n"
                            + "}\n"
                            + ".glyphicon-sound-dolby:before {\n"
                            + "  content: \"\\e190\";\n"
                            + "}\n"
                            + ".glyphicon-sound-5-1:before {\n"
                            + "  content: \"\\e191\";\n"
                            + "}\n"
                            + ".glyphicon-sound-6-1:before {\n"
                            + "  content: \"\\e192\";\n"
                            + "}\n"
                            + ".glyphicon-sound-7-1:before {\n"
                            + "  content: \"\\e193\";\n"
                            + "}\n"
                            + ".glyphicon-copyright-mark:before {\n"
                            + "  content: \"\\e194\";\n"
                            + "}\n"
                            + ".glyphicon-registration-mark:before {\n"
                            + "  content: \"\\e195\";\n"
                            + "}\n"
                            + ".glyphicon-cloud-download:before {\n"
                            + "  content: \"\\e197\";\n"
                            + "}\n"
                            + ".glyphicon-cloud-upload:before {\n"
                            + "  content: \"\\e198\";\n"
                            + "}\n"
                            + ".glyphicon-tree-conifer:before {\n"
                            + "  content: \"\\e199\";\n"
                            + "}\n"
                            + ".glyphicon-tree-deciduous:before {\n"
                            + "  content: \"\\e200\";\n"
                            + "}\n"
                            + ".glyphicon-cd:before {\n"
                            + "  content: \"\\e201\";\n"
                            + "}\n"
                            + ".glyphicon-save-file:before {\n"
                            + "  content: \"\\e202\";\n"
                            + "}\n"
                            + ".glyphicon-open-file:before {\n"
                            + "  content: \"\\e203\";\n"
                            + "}\n"
                            + ".glyphicon-level-up:before {\n"
                            + "  content: \"\\e204\";\n"
                            + "}\n"
                            + ".glyphicon-copy:before {\n"
                            + "  content: \"\\e205\";\n"
                            + "}\n"
                            + ".glyphicon-paste:before {\n"
                            + "  content: \"\\e206\";\n"
                            + "}\n"
                            + ".glyphicon-alert:before {\n"
                            + "  content: \"\\e209\";\n"
                            + "}\n"
                            + ".glyphicon-equalizer:before {\n"
                            + "  content: \"\\e210\";\n"
                            + "}\n"
                            + ".glyphicon-king:before {\n"
                            + "  content: \"\\e211\";\n"
                            + "}\n"
                            + ".glyphicon-queen:before {\n"
                            + "  content: \"\\e212\";\n"
                            + "}\n"
                            + ".glyphicon-pawn:before {\n"
                            + "  content: \"\\e213\";\n"
                            + "}\n"
                            + ".glyphicon-bishop:before {\n"
                            + "  content: \"\\e214\";\n"
                            + "}\n"
                            + ".glyphicon-knight:before {\n"
                            + "  content: \"\\e215\";\n"
                            + "}\n"
                            + ".glyphicon-baby-formula:before {\n"
                            + "  content: \"\\e216\";\n"
                            + "}\n"
                            + ".glyphicon-tent:before {\n"
                            + "  content: \"\\26fa\";\n"
                            + "}\n"
                            + ".glyphicon-blackboard:before {\n"
                            + "  content: \"\\e218\";\n"
                            + "}\n"
                            + ".glyphicon-bed:before {\n"
                            + "  content: \"\\e219\";\n"
                            + "}\n"
                            + ".glyphicon-apple:before {\n"
                            + "  content: \"\\f8ff\";\n"
                            + "}\n"
                            + ".glyphicon-erase:before {\n"
                            + "  content: \"\\e221\";\n"
                            + "}\n"
                            + ".glyphicon-hourglass:before {\n"
                            + "  content: \"\\231b\";\n"
                            + "}\n"
                            + ".glyphicon-lamp:before {\n"
                            + "  content: \"\\e223\";\n"
                            + "}\n"
                            + ".glyphicon-duplicate:before {\n"
                            + "  content: \"\\e224\";\n"
                            + "}\n"
                            + ".glyphicon-piggy-bank:before {\n"
                            + "  content: \"\\e225\";\n"
                            + "}\n"
                            + ".glyphicon-scissors:before {\n"
                            + "  content: \"\\e226\";\n"
                            + "}\n"
                            + ".glyphicon-bitcoin:before {\n"
                            + "  content: \"\\e227\";\n"
                            + "}\n"
                            + ".glyphicon-btc:before {\n"
                            + "  content: \"\\e227\";\n"
                            + "}\n"
                            + ".glyphicon-xbt:before {\n"
                            + "  content: \"\\e227\";\n"
                            + "}\n"
                            + ".glyphicon-yen:before {\n"
                            + "  content: \"\\00a5\";\n"
                            + "}\n"
                            + ".glyphicon-jpy:before {\n"
                            + "  content: \"\\00a5\";\n"
                            + "}\n"
                            + ".glyphicon-ruble:before {\n"
                            + "  content: \"\\20bd\";\n"
                            + "}\n"
                            + ".glyphicon-rub:before {\n"
                            + "  content: \"\\20bd\";\n"
                            + "}\n"
                            + ".glyphicon-scale:before {\n"
                            + "  content: \"\\e230\";\n"
                            + "}\n"
                            + ".glyphicon-ice-lolly:before {\n"
                            + "  content: \"\\e231\";\n"
                            + "}\n"
                            + ".glyphicon-ice-lolly-tasted:before {\n"
                            + "  content: \"\\e232\";\n"
                            + "}\n"
                            + ".glyphicon-education:before {\n"
                            + "  content: \"\\e233\";\n"
                            + "}\n"
                            + ".glyphicon-option-horizontal:before {\n"
                            + "  content: \"\\e234\";\n"
                            + "}\n"
                            + ".glyphicon-option-vertical:before {\n"
                            + "  content: \"\\e235\";\n"
                            + "}\n"
                            + ".glyphicon-menu-hamburger:before {\n"
                            + "  content: \"\\e236\";\n"
                            + "}\n"
                            + ".glyphicon-modal-window:before {\n"
                            + "  content: \"\\e237\";\n"
                            + "}\n"
                            + ".glyphicon-oil:before {\n"
                            + "  content: \"\\e238\";\n"
                            + "}\n"
                            + ".glyphicon-grain:before {\n"
                            + "  content: \"\\e239\";\n"
                            + "}\n"
                            + ".glyphicon-sunglasses:before {\n"
                            + "  content: \"\\e240\";\n"
                            + "}\n"
                            + ".glyphicon-text-size:before {\n"
                            + "  content: \"\\e241\";\n"
                            + "}\n"
                            + ".glyphicon-text-color:before {\n"
                            + "  content: \"\\e242\";\n"
                            + "}\n"
                            + ".glyphicon-text-background:before {\n"
                            + "  content: \"\\e243\";\n"
                            + "}\n"
                            + ".glyphicon-object-align-top:before {\n"
                            + "  content: \"\\e244\";\n"
                            + "}\n"
                            + ".glyphicon-object-align-bottom:before {\n"
                            + "  content: \"\\e245\";\n"
                            + "}\n"
                            + ".glyphicon-object-align-horizontal:before {\n"
                            + "  content: \"\\e246\";\n"
                            + "}\n"
                            + ".glyphicon-object-align-left:before {\n"
                            + "  content: \"\\e247\";\n"
                            + "}\n"
                            + ".glyphicon-object-align-vertical:before {\n"
                            + "  content: \"\\e248\";\n"
                            + "}\n"
                            + ".glyphicon-object-align-right:before {\n"
                            + "  content: \"\\e249\";\n"
                            + "}\n"
                            + ".glyphicon-triangle-right:before {\n"
                            + "  content: \"\\e250\";\n"
                            + "}\n"
                            + ".glyphicon-triangle-left:before {\n"
                            + "  content: \"\\e251\";\n"
                            + "}\n"
                            + ".glyphicon-triangle-bottom:before {\n"
                            + "  content: \"\\e252\";\n"
                            + "}\n"
                            + ".glyphicon-triangle-top:before {\n"
                            + "  content: \"\\e253\";\n"
                            + "}\n"
                            + ".glyphicon-console:before {\n"
                            + "  content: \"\\e254\";\n"
                            + "}\n"
                            + ".glyphicon-superscript:before {\n"
                            + "  content: \"\\e255\";\n"
                            + "}\n"
                            + ".glyphicon-subscript:before {\n"
                            + "  content: \"\\e256\";\n"
                            + "}\n"
                            + ".glyphicon-menu-left:before {\n"
                            + "  content: \"\\e257\";\n"
                            + "}\n"
                            + ".glyphicon-menu-right:before {\n"
                            + "  content: \"\\e258\";\n"
                            + "}\n"
                            + ".glyphicon-menu-down:before {\n"
                            + "  content: \"\\e259\";\n"
                            + "}\n"
                            + ".glyphicon-menu-up:before {\n"
                            + "  content: \"\\e260\";\n"
                            + "}\n"
                            + "* {\n"
                            + "  -webkit-box-sizing: border-box;\n"
                            + "  -moz-box-sizing: border-box;\n"
                            + "  box-sizing: border-box;\n"
                            + "}\n"
                            + "*:before,\n"
                            + "*:after {\n"
                            + "  -webkit-box-sizing: border-box;\n"
                            + "  -moz-box-sizing: border-box;\n"
                            + "  box-sizing: border-box;\n"
                            + "}\n"
                            + "html {\n"
                            + "  font-size: 10px;\n"
                            + "  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n"
                            + "}\n"
                            + "body {\n"
                            + "  font-family: \"Source Sans Pro\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
                            + "  font-size: 14px;\n"
                            + "  line-height: 1.42857143;\n"
                            + "  color: #555555;\n"
                            + "  background-color: #ffffff;\n"
                            + "}\n"
                            + "input,\n"
                            + "button,\n"
                            + "select,\n"
                            + "textarea {\n"
                            + "  font-family: inherit;\n"
                            + "  font-size: inherit;\n"
                            + "  line-height: inherit;\n"
                            + "}\n"
                            + "a {\n"
                            + "  color: #158cba;\n"
                            + "  text-decoration: none;\n"
                            + "}\n"
                            + "a:hover,\n"
                            + "a:focus {\n"
                            + "  color: #158cba;\n"
                            + "  text-decoration: underline;\n"
                            + "}\n"
                            + "a:focus {\n"
                            + "  outline: 5px auto -webkit-focus-ring-color;\n"
                            + "  outline-offset: -2px;\n"
                            + "}\n"
                            + "figure {\n"
                            + "  margin: 0;\n"
                            + "}\n"
                            + "img {\n"
                            + "  vertical-align: middle;\n"
                            + "}\n"
                            + ".img-responsive,\n"
                            + ".thumbnail > img,\n"
                            + ".thumbnail a > img,\n"
                            + ".carousel-inner > .item > img,\n"
                            + ".carousel-inner > .item > a > img {\n"
                            + "  display: block;\n"
                            + "  max-width: 100%;\n"
                            + "  height: auto;\n"
                            + "}\n"
                            + ".img-rounded {\n"
                            + "  border-radius: 5px;\n"
                            + "}\n"
                            + ".img-thumbnail {\n"
                            + "  padding: 4px;\n"
                            + "  line-height: 1.42857143;\n"
                            + "  background-color: #ffffff;\n"
                            + "  border: 1px solid #eeeeee;\n"
                            + "  border-radius: 4px;\n"
                            + "  -webkit-transition: all 0.2s ease-in-out;\n"
                            + "  -o-transition: all 0.2s ease-in-out;\n"
                            + "  transition: all 0.2s ease-in-out;\n"
                            + "  display: inline-block;\n"
                            + "  max-width: 100%;\n"
                            + "  height: auto;\n"
                            + "}\n"
                            + ".img-circle {\n"
                            + "  border-radius: 50%;\n"
                            + "}\n"
                            + "hr {\n"
                            + "  margin-top: 20px;\n"
                            + "  margin-bottom: 20px;\n"
                            + "  border: 0;\n"
                            + "  border-top: 1px solid #eeeeee;\n"
                            + "}\n"
                            + ".sr-only {\n"
                            + "  position: absolute;\n"
                            + "  width: 1px;\n"
                            + "  height: 1px;\n"
                            + "  margin: -1px;\n"
                            + "  padding: 0;\n"
                            + "  overflow: hidden;\n"
                            + "  clip: rect(0, 0, 0, 0);\n"
                            + "  border: 0;\n"
                            + "}\n"
                            + ".sr-only-focusable:active,\n"
                            + ".sr-only-focusable:focus {\n"
                            + "  position: static;\n"
                            + "  width: auto;\n"
                            + "  height: auto;\n"
                            + "  margin: 0;\n"
                            + "  overflow: visible;\n"
                            + "  clip: auto;\n"
                            + "}\n"
                            + "[role=\"button\"] {\n"
                            + "  cursor: pointer;\n"
                            + "}\n"
                            + "h1,\n"
                            + "h2,\n"
                            + "h3,\n"
                            + "h4,\n"
                            + "h5,\n"
                            + "h6,\n"
                            + ".h1,\n"
                            + ".h2,\n"
                            + ".h3,\n"
                            + ".h4,\n"
                            + ".h5,\n"
                            + ".h6 {\n"
                            + "  font-family: inherit;\n"
                            + "  font-weight: 400;\n"
                            + "  line-height: 1.1;\n"
                            + "  color: #333333;\n"
                            + "}\n"
                            + "h1 small,\n"
                            + "h2 small,\n"
                            + "h3 small,\n"
                            + "h4 small,\n"
                            + "h5 small,\n"
                            + "h6 small,\n"
                            + ".h1 small,\n"
                            + ".h2 small,\n"
                            + ".h3 small,\n"
                            + ".h4 small,\n"
                            + ".h5 small,\n"
                            + ".h6 small,\n"
                            + "h1 .small,\n"
                            + "h2 .small,\n"
                            + "h3 .small,\n"
                            + "h4 .small,\n"
                            + "h5 .small,\n"
                            + "h6 .small,\n"
                            + ".h1 .small,\n"
                            + ".h2 .small,\n"
                            + ".h3 .small,\n"
                            + ".h4 .small,\n"
                            + ".h5 .small,\n"
                            + ".h6 .small {\n"
                            + "  font-weight: normal;\n"
                            + "  line-height: 1;\n"
                            + "  color: #999999;\n"
                            + "}\n"
                            + "h1,\n"
                            + ".h1,\n"
                            + "h2,\n"
                            + ".h2,\n"
                            + "h3,\n"
                            + ".h3 {\n"
                            + "  margin-top: 20px;\n"
                            + "  margin-bottom: 10px;\n"
                            + "}\n"
                            + "h1 small,\n"
                            + ".h1 small,\n"
                            + "h2 small,\n"
                            + ".h2 small,\n"
                            + "h3 small,\n"
                            + ".h3 small,\n"
                            + "h1 .small,\n"
                            + ".h1 .small,\n"
                            + "h2 .small,\n"
                            + ".h2 .small,\n"
                            + "h3 .small,\n"
                            + ".h3 .small {\n"
                            + "  font-size: 65%;\n"
                            + "}\n"
                            + "h4,\n"
                            + ".h4,\n"
                            + "h5,\n"
                            + ".h5,\n"
                            + "h6,\n"
                            + ".h6 {\n"
                            + "  margin-top: 10px;\n"
                            + "  margin-bottom: 10px;\n"
                            + "}\n"
                            + "h4 small,\n"
                            + ".h4 small,\n"
                            + "h5 small,\n"
                            + ".h5 small,\n"
                            + "h6 small,\n"
                            + ".h6 small,\n"
                            + "h4 .small,\n"
                            + ".h4 .small,\n"
                            + "h5 .small,\n"
                            + ".h5 .small,\n"
                            + "h6 .small,\n"
                            + ".h6 .small {\n"
                            + "  font-size: 75%;\n"
                            + "}\n"
                            + "h1,\n"
                            + ".h1 {\n"
                            + "  font-size: 36px;\n"
                            + "}\n"
                            + "h2,\n"
                            + ".h2 {\n"
                            + "  font-size: 30px;\n"
                            + "}\n"
                            + "h3,\n"
                            + ".h3 {\n"
                            + "  font-size: 24px;\n"
                            + "}\n"
                            + "h4,\n"
                            + ".h4 {\n"
                            + "  font-size: 18px;\n"
                            + "}\n"
                            + "h5,\n"
                            + ".h5 {\n"
                            + "  font-size: 14px;\n"
                            + "}\n"
                            + "h6,\n"
                            + ".h6 {\n"
                            + "  font-size: 12px;\n"
                            + "}\n"
                            + "p {\n"
                            + "  margin: 0 0 10px;\n"
                            + "}\n"
                            + ".lead {\n"
                            + "  margin-bottom: 20px;\n"
                            + "  font-size: 16px;\n"
                            + "  font-weight: 300;\n"
                            + "  line-height: 1.4;\n"
                            + "}\n"
                            + "@media (min-width: 768px) {\n"
                            + "  .lead {\n"
                            + "    font-size: 21px;\n"
                            + "  }\n"
                            + "}\n"
                            + "small,\n"
                            + ".small {\n"
                            + "  font-size: 85%;\n"
                            + "}\n"
                            + "mark,\n"
                            + ".mark {\n"
                            + "  background-color: #ff851b;\n"
                            + "  padding: .2em;\n"
                            + "}\n"
                            + ".text-left {\n"
                            + "  text-align: left;\n"
                            + "}\n"
                            + ".text-right {\n"
                            + "  text-align: right;\n"
                            + "}\n"
                            + ".text-center {\n"
                            + "  text-align: center;\n"
                            + "}\n"
                            + ".text-justify {\n"
                            + "  text-align: justify;\n"
                            + "}\n"
                            + ".text-nowrap {\n"
                            + "  white-space: nowrap;\n"
                            + "}\n"
                            + ".text-lowercase {\n"
                            + "  text-transform: lowercase;\n"
                            + "}\n"
                            + ".text-uppercase {\n"
                            + "  text-transform: uppercase;\n"
                            + "}\n"
                            + ".text-capitalize {\n"
                            + "  text-transform: capitalize;\n"
                            + "}\n"
                            + ".text-muted {\n"
                            + "  color: #999999;\n"
                            + "}\n"
                            + ".text-primary {\n"
                            + "  color: #158cba;\n"
                            + "}\n"
                            + "a.text-primary:hover,\n"
                            + "a.text-primary:focus {\n"
                            + "  color: #106a8c;\n"
                            + "}\n"
                            + ".text-success {\n"
                            + "  color: #ffffff;\n"
                            + "}\n"
                            + "a.text-success:hover,\n"
                            + "a.text-success:focus {\n"
                            + "  color: #e6e6e6;\n"
                            + "}\n"
                            + ".text-info {\n"
                            + "  color: #ffffff;\n"
                            + "}\n"
                            + "a.text-info:hover,\n"
                            + "a.text-info:focus {\n"
                            + "  color: #e6e6e6;\n"
                            + "}\n"
                            + ".text-warning {\n"
                            + "  color: #ffffff;\n"
                            + "}\n"
                            + "a.text-warning:hover,\n"
                            + "a.text-warning:focus {\n"
                            + "  color: #e6e6e6;\n"
                            + "}\n"
                            + ".text-danger {\n"
                            + "  color: #ffffff;\n"
                            + "}\n"
                            + "a.text-danger:hover,\n"
                            + "a.text-danger:focus {\n"
                            + "  color: #e6e6e6;\n"
                            + "}\n"
                            + ".bg-primary {\n"
                            + "  color: #fff;\n"
                            + "  background-color: #158cba;\n"
                            + "}\n"
                            + "a.bg-primary:hover,\n"
                            + "a.bg-primary:focus {\n"
                            + "  background-color: #106a8c;\n"
                            + "}\n"
                            + ".bg-success {\n"
                            + "  background-color: #28b62c;\n"
                            + "}\n"
                            + "a.bg-success:hover,\n"
                            + "a.bg-success:focus {\n"
                            + "  background-color: #1f8c22;\n"
                            + "}\n"
                            + ".bg-info {\n"
                            + "  background-color: #75caeb;\n"
                            + "}\n"
                            + "a.bg-info:hover,\n"
                            + "a.bg-info:focus {\n"
                            + "  background-color: #48b9e5;\n"
                            + "}\n"
                            + ".bg-warning {\n"
                            + "  background-color: #ff851b;\n"
                            + "}\n"
                            + "a.bg-warning:hover,\n"
                            + "a.bg-warning:focus {\n"
                            + "  background-color: #e76b00;\n"
                            + "}\n"
                            + ".bg-danger {\n"
                            + "  background-color: #ff4136;\n"
                            + "}\n"
                            + "a.bg-danger:hover,\n"
                            + "a.bg-danger:focus {\n"
                            + "  background-color: #ff1103;\n"
                            + "}"
                            + ".container {\n"
                            + "  margin-right: auto;\n"
                            + "  margin-left: auto;\n"
                            + "  padding-left: 15px;\n"
                            + "  padding-right: 15px;\n"
                            + "}\n"
                            + "@media (min-width: 768px) {\n"
                            + "  .container {\n"
                            + "    width: 750px;\n"
                            + "  }\n"
                            + "}\n"
                            + "@media (min-width: 992px) {\n"
                            + "  .container {\n"
                            + "    width: 970px;\n"
                            + "  }\n"
                            + "}\n"
                            + "@media (min-width: 1200px) {\n"
                            + "  .container {\n"
                            + "    width: 1170px;\n"
                            + "  }\n"
                            + "}\n"
                            + ".container-fluid {\n"
                            + "  margin-right: auto;\n"
                            + "  margin-left: auto;\n"
                            + "  padding-left: 15px;\n"
                            + "  padding-right: 15px;\n"
                            + "}\n"
                            + ".row {\n"
                            + "  margin-left: -15px;\n"
                            + "  margin-right: -15px;\n"
                            + "}"
                            + ".btn {\n"
                            + "  display: inline-block;\n"
                            + "  margin-bottom: 0;\n"
                            + "  font-weight: normal;\n"
                            + "  text-align: center;\n"
                            + "  vertical-align: middle;\n"
                            + "  -ms-touch-action: manipulation;\n"
                            + "      touch-action: manipulation;\n"
                            + "  cursor: pointer;\n"
                            + "  background-image: none;\n"
                            + "  border: 1px solid transparent;\n"
                            + "  white-space: nowrap;\n"
                            + "  padding: 7px 12px;\n"
                            + "  font-size: 14px;\n"
                            + "  line-height: 1.42857143;\n"
                            + "  border-radius: 4px;\n"
                            + "  -webkit-user-select: none;\n"
                            + "  -moz-user-select: none;\n"
                            + "  -ms-user-select: none;\n"
                            + "  user-select: none;\n"
                            + "}\n"
                            + ".btn:focus,\n"
                            + ".btn:active:focus,\n"
                            + ".btn.active:focus,\n"
                            + ".btn.focus,\n"
                            + ".btn:active.focus,\n"
                            + ".btn.active.focus {\n"
                            + "  outline: 5px auto -webkit-focus-ring-color;\n"
                            + "  outline-offset: -2px;\n"
                            + "}\n"
                            + ".btn:hover,\n"
                            + ".btn:focus,\n"
                            + ".btn.focus {\n"
                            + "  color: #555555;\n"
                            + "  text-decoration: none;\n"
                            + "}\n"
                            + ".btn:active,\n"
                            + ".btn.active {\n"
                            + "  outline: 0;\n"
                            + "  background-image: none;\n"
                            + "  -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);\n"
                            + "  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);\n"
                            + "}\n"
                            + ".btn.disabled,\n"
                            + ".btn[disabled],\n"
                            + "fieldset[disabled] .btn {\n"
                            + "  cursor: not-allowed;\n"
                            + "  opacity: 0.65;\n"
                            + "  filter: alpha(opacity=65);\n"
                            + "  -webkit-box-shadow: none;\n"
                            + "  box-shadow: none;\n"
                            + "}\n"
                            + "a.btn.disabled,\n"
                            + "fieldset[disabled] a.btn {\n"
                            + "  pointer-events: none;\n"
                            + "}"
                            + "@font-face {\n"
                            + "  font-family: 'Glyphicons Halflings';\n"
                            + "  src: url('../fonts/glyphicons-halflings-regular.eot');\n"
                            + "  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');\n"
                            + "}\n"
                            + ".glyphicon {\n"
                            + "  position: relative;\n"
                            + "  top: 1px;\n"
                            + "  display: inline-block;\n"
                            + "  font-family: 'Glyphicons Halflings';\n"
                            + "  font-style: normal;\n"
                            + "  font-weight: normal;\n"
                            + "  line-height: 1;\n"
                            + "  -webkit-font-smoothing: antialiased;\n"
                            + "  -moz-osx-font-smoothing: grayscale;\n"
                            + "}"
                            + ".glyphicon-home:before {\n"
                            + "  content: \"\\e021\";\n"
                            + "}"
                            + " </style>\n"
                            + "</head>"
                            + "<body>"
                            + "<div class=\"container\">\n"
                            + "    <div class=\"row\">\n"
                            + "        <div class=\"col-md-12\">\n"
                            + "            <div class=\"error-template\">\n"
                            + "                <div class=\"error-details\">\n"
                            + "                     <h1> " + messageThrowable + "</h1>\n"
                            + "                </div>\n"
                            + "                <div class=\"error-actions\">\n"
                            + "                    <a href=\"/go/to/home.xhtml\" class=\"btn btn-primary btn-lg\">\n Volver a la pagina principal</a>"
                            + "                </div>\n"
                            + "            </div>\n"
                            + "        </div>\n"
                            + "    </div>\n"
                            + "</div>"
                            + "</body>"
                    );
                    printWriter.print(html.toString());
                    printWriter.close();
                    printStream.close();
                    response.getOutputStream().close();
                } catch (IOException ex) {
                    logger.error(ex);
                }
            } else {
                PrintStream ps = null;
                try {
                    ps = new PrintStream(response.getOutputStream());
                    t.printStackTrace(ps);
                    response.getOutputStream().close();
                } catch (IOException ex) {
                    logger.error(ex);
                } finally {
                    if (ps != null) {
                        ps.close();
                    }
                }
            }

        } finally {
            logger.debug("FINALIZA METODO - sendProcessingError()");
        }

    }

}
